language: "node_js"

node_js:
  - "4"
  - "6"
  - "7"

script:
  - "npm test"

after_success:
  - "npm run coveralls"

notifications:
  email: false
  slack:
    rooms:
      - moeriki:Gqf2TnMQj95R0y9cNLQhw6Eo#updates
    on_success: change
    on_failure: always
